In [26]:
import numpy as np
#Method 1,2,3 and 4
arry = np.arange(10)
print("Method 1 Create Array with 0 to 99 range Element")
print(arry)
print()

zeroArry = np.zeros(10)
print("Method 2 Create Array with 0 value all Element")
print(zeroArry)
print()

oneArry = np.ones(10)
print("Method 3 Create Array with 1 value all Element")
print(oneArry)
print()

emptyArray = np.empty(10)
print("Method 4 Create Array with random value all Element")
print(emptyArray)
print()

#Method 5,6,7,8,9 and 10
print("Method 5 Change 1d Array to 2d Array 2 Rows and 5 Cols")
arry2 = arry.reshape(2,5)
print(arry2)
print()

print("Method 6 Check Shape")
print(arry2.shape)
print()

print("Method 7 Check Dimenstions")
print(arry2.ndim)
print()

print("Method 8 Check Data Type of an array")
print(arry2.dtype.name)
print()

print("Method 9 Check Item Size Of An array")
print(arry2.itemsize)
print()

print("Method 10 Check how much Element in an array")
print(arry2.size)
print()

#Method 11
print("Method 11")
print(np.dtype([('ali', np.int16)]))
print()

#Method 12,13,14,15
b = np.array([[1.2,-7.3,9.4],
              [8.,-5.,5.],
              [1.,-7.,9.],
              [-8.,5.,5.],
              [1.,7.,-9.]])
c = np.array([[1,-7,9],
              [8,-5,5],
              [1,-7,9],
              [-8,5,5],
              [1,7,-9]])
print("Method 12 Compute absolute value All Element in an array")
print(np.fabs(b))
print()

print("Method 13 Compute absolute value All Element in an array and Convert into Floating point")
print(np.fabs(c))
print()

print("Method 14 Square Root All Element in an array")
print(np.sqrt(b))
print()

print("Method 15 Square all Element in an array")
print(np.square(b))
print()

print("Method 16 Exponent all Element in an array")
print(np.exp(b))
print()


print("Method 17 Logarithm all Element in an array")
print(np.log(b))
print()


print("Method 18 Logarithm Base 10 all Element in an array")
print(np.log10(b))
print()


print("Method 19 Logarithm Base 2 all Element in an array")
print(np.log2(b))
print()

print("Method 20")
print(np.sign(b))
print()

print("Method 21 Square all Element in an array")
print(np.ceil(b))
print()

print("Method 22 Square all Element in an array")
print(np.floor(b))
print()

print("Method 23 Round all Element in an array")
print(np.rint(b))
print()

print("Method 24 Create 2 array one for Fractional value and second one for integer part")
print(np.modf(b))
print()

print("Method 25 Check Element is not a number")
print(np.isnan(b))
print()

print("Method 26 Check Element is finite")
print(np.isfinite(b))
print()

print("Method 27 Check Element is infinite")
print(np.isinf(b))
print()

#Method
print("Method 28 Transpose array")
print(b.transpose())
print()

Method 1 Create Array with 0 to 99 range Element
[0 1 2 3 4 5 6 7 8 9]

Method 2 Create Array with 0 value all Element
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Method 3 Create Array with 1 value all Element
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Method 4 Create Array with random value all Element
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Method 5 Change 1d Array to 2d Array 10 Rows and 10 Cols
[[0 1 2 3 4]
 [5 6 7 8 9]]

Method 6 Check Shape
(2, 5)

Method 7 Check Dimenstions
2

Method 8 Check Data Type of an array
int32

Method 9 Check Item Size Of An array
4

Method 10 Check how much Element in an array
10

Method 11
[('ali', '<i2')]

Method 12 Compute absolute value All Element in an array
[[1.2 7.3 9.4]
 [8.  5.  5. ]
 [1.  7.  9. ]
 [8.  5.  5. ]
 [1.  7.  9. ]]

Method 13 Compute absolute value All Element in an array and Convert into Floating point
[[1. 7. 9.]
 [8. 5. 5.]
 [1. 7. 9.]
 [8. 5. 5.]
 [1. 7. 9.]]

Method 14 Square Root All Element in an array
[[1.09544512        nan 3.06594194]
 [2.8284271

<ipython-input-26-41fc897146d3>:74: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(b))
<ipython-input-26-41fc897146d3>:87: RuntimeWarning: invalid value encountered in log
  print(np.log(b))
<ipython-input-26-41fc897146d3>:92: RuntimeWarning: invalid value encountered in log10
  print(np.log10(b))
<ipython-input-26-41fc897146d3>:97: RuntimeWarning: invalid value encountered in log2
  print(np.log2(b))
